### ISSUE TITLE
"Not a valid file" Error

### ISSUE THREAD

**Issue by mohamedhaddi** [alexandregv/norminette-vim#1] opened 2021-01-26 19:40 UTC
Hi!

I installed the plugin and tried it with some C files in my home directory, the linter works just fine. But then when I tried it with other C files in some other directories that are still under the home directory it didn't work, instead it tells me on file open:
![image](https://user-images.githubusercontent.com/6943864/105895684-1999f800-6016-11eb-9edc-67e4b2aa41ab.png)

Same thing when I type :Errors
![image](https://user-images.githubusercontent.com/6943864/105895754-30404f00-6016-11eb-864d-c110af7dc41c.png)

I have the Norminette installed in my home directory: `~/.norminette/norminette.rb`

This is my configuration: 
```vim
" Enable norminette-vim (and clang)
let g:syntastic_c_checkers = ['norminette', 'clang']
let g:syntastic_aggregate_errors = 1

" Set the path to norminette (do no set if using norminette of 42 mac)
let g:syntastic_c_norminette_exec = '~/.norminette/norminette.rb'

" Support headers (.h)
let g:c_syntax_for_h = 1
let g:syntastic_c_include_dirs = ['include', '../include', '../../include', 'libft', '../libft/include', '../../libft/include']

" Pass custom arguments to norminette
let g:syntastic_c_norminette_args = '-R CheckForbiddenSourceHeader'

" Check errors when opening a file (disable to speed up startup time)
let g:syntastic_check_on_open = 1

" Enable error list
" let g:syntastic_always_populate_loc_list = 1

" Automatically open error list
" let g:syntastic_auto_loc_list = 1

" Skip check when closing
let g:syntastic_check_on_wq = 0
```

My host runs Pengwin (Debian-based distro) on WSL2.

**Comment by alexandregv** [comment] 2021-02-13 18:25
Hi, thanks for the report
Unfortunately, I can't manage to reproduce the bug locally

I reproduced your setup from your screenshot, with a folder under my home, a sub-folder named `src`, and a `test.c` file opened from the main folder. It works correctly for me, showing me a correct norm error.

![image](https://user-images.githubusercontent.com/10067226/107858204-4e3dea00-6e33-11eb-8765-207f287490d5.png)

![image](https://user-images.githubusercontent.com/10067226/107857938-a96edd00-6e31-11eb-9691-1dea79db9fb1.png)

I notice you use WSL2, maybe this could be related. Is your file or the directory a symlink? Or whatever else "strange" related to the filesystem? WSL2 has stranges issues with fs...

**Comment by mohamedhaddi** [comment] 2021-02-14 21:37
Hey! Thanks for reporting back.

I also now retried the same steps you did and the plugin did work this time, but after comparing this setup with the one I originally faced the issue with, I figured it might have to do with the "nested" git repositories, I reproduced a similar setup and had the same issue, so it is very likely related to that, but I'm not sure if it's an issue just with WSL2 (and they're not symlinks).

The listing I first faced the issue with is:

![image](https://user-images.githubusercontent.com/6943864/107889459-0ee6ca80-6f13-11eb-965f-19aeb183eb4d.png)

Where my home directory is a git repository, inside it there is my directory `1337_projects` which contains another git repository `cub3d`, and this is where the issue happens.

I could reproduce the same issue by creating another directory inside my home directory (which, like a said, is a git repo), and `git init` within it:

![image](https://user-images.githubusercontent.com/6943864/107889610-27a3b000-6f14-11eb-8ad0-366875bb55fc.png)


![image](https://user-images.githubusercontent.com/6943864/107889591-0cd13b80-6f14-11eb-9248-38403f112e02.png)

**Comment by alexandregv** [comment] 2021-02-14 23:02
Hi, thanks for the detailed infos!

I reproduced your setup on my arch install and also on WSL2 (Ubuntu 18.04), but couldn't manage to reproduce the bug :/
I couldn't try on Pengwin since it seems to be paid.
Does the norminette work on the file when launched via command line?

Archlinux:
![image](https://user-images.githubusercontent.com/10067226/107891613-1e204500-6f20-11eb-9b87-2923ebdc708c.png)
![image](https://user-images.githubusercontent.com/10067226/107891635-3a23e680-6f20-11eb-8548-e07672bf350b.png)

WSL2 (Ubuntu 18.04):
![image](https://user-images.githubusercontent.com/10067226/107891734-d2ba6680-6f20-11eb-9c2a-880fa55494fa.png)
![image](https://user-images.githubusercontent.com/10067226/107891736-d6e68400-6f20-11eb-96d8-8cb8bbcf5961.png)

**Comment by mohamedhaddi** [comment] 2021-02-14 23:45
That's really weird, thanks for testing on your end, running the norminette via cli works just fine:

![image](https://user-images.githubusercontent.com/6943864/107892538-1499db80-6f26-11eb-8b5b-227ece389d81.png)

But the linter still doesn't "recognize" it:

![image](https://user-images.githubusercontent.com/6943864/107892783-9c341a00-6f27-11eb-8a6b-802a65c5b446.png)

Also running :Norminette as vim command works fine too on the same file:

![image](https://user-images.githubusercontent.com/6943864/107892591-7a866300-6f26-11eb-8709-00603206af47.png)

Another detail I might have missed is that I'm using neovim, not sure how this could affect it since the linter **does** work normally in use cases that don't involve nested git repos, but it might be worth testing if you have neovim installed, I'll test as well on my end with ordinary vim.

Otherwise I'll keep this issue updated as I find out more.

**Comment by mohamedhaddi** [comment] 2021-02-15 00:06
Update:

I installed the plugin in a fresh (with no other plugins), ordinary vim (instead of neovim) and it turned out there is no issue with it. So I'm left with two conclusions, it's either a problem with neovim itself (which I doubt) or some kind of conflict with other plugin(s) that are installed in my neovim:

![image](https://user-images.githubusercontent.com/6943864/107893172-efa76780-6f29-11eb-9db8-0329e3ee370a.png)

I'll try to disable them one by one and report back as soon as I find the culprit.

**Comment by alexandregv** [comment] 2021-02-15 00:09
I'm also using neovim, so this shouldn't be the problem.
Guess you will have to do the classic "plugin-by-plugin" debug haha
Really strange that another plugin could be in conflict, and even more strange considering it triggers a "Not a valid file" error, like if it had changed the file..

Just in case, here are the plugins I use:
```vim
call plug#begin('~/.vim/plugged')
Plug 'vim-syntastic/syntastic'
Plug 'alexandregv/norminette-vim'
Plug 'scrooloose/nerdtree'
" Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'ryanoasis/vim-devicons'
Plug 'Lenovsky/nuake'
Plug 'pandark/42header.vim'
Plug 'ekalinin/Dockerfile.vim'
Plug 'brookhong/cscope.vim'
Plug 'itchyny/lightline.vim'
Plug 'sheerun/vim-polyglot'
Plug 'scrooloose/nerdcommenter'
Plug 'mbbill/undotree'
Plug 'terryma/vim-multiple-cursors'
Plug 'thaerkh/vim-workspace'
Plug 'drewtempelmeyer/palenight.vim'
" Plug 'arcticicestudio/nord-vim'
" Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'mattn/emmet-vim'
Plug 'christoomey/vim-tmux-navigator'
Plug 'elixir-editors/vim-elixir'
Plug 'mhinz/vim-mix-format'
Plug 'edkolev/tmuxline.vim'
Plug 'rbgrouleff/bclose.vim'
Plug 'francoiscabrol/ranger.vim'
Plug 'junegunn/vim-easy-align'
Plug 'jparise/vim-graphql'
"Plug 'mxw/vim-jsx'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'ctrlpvim/ctrlp.vim'
Plug 'rizzatti/dash.vim'
Plug 'easymotion/vim-easymotion'
Plug 'vim-scripts/Align'
" Plug 'itchyny/vim-gof'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'junegunn/rainbow_parentheses.vim'
Plug 'wlemuel/vim-tldr'
call plug#end()
```

Obviously it also works fine with only syntastic and norminette-vim

The difference with `:Norminette` is that it's using a native feature of vim instead of syntastic (compiler + quickfix).

**Comment by mohamedhaddi** [comment] 2021-02-15 01:08
> and even more strange considering it triggers a "Not a valid file" error, like if it had changed the file..

And even more strange is the fact that it only happens with nested git repos!

> Guess you will have to do the classic "plugin-by-plugin" debug haha

Well that was painful to say the least :p especially that I didn't find the bad guy in my `init.vim` after commenting out every plugin and configuration, but it was a plugin that I installed manually in `.config/nvim/plugin` called [vim-rooter](https://github.com/airblade/vim-rooter), it basically makes sure you're on the root directory of the project of the file you just opened, for example if I open `~/test/test.c` from my home and then opened NerdTree, `test/` will be the root directory in NerdTree because vim-rooter identified it as the project root for `test.c` (I guess it does so by walking up the tree and stopping by the first git repo found or something, although it's probably more intricate than that), so I'm not sure what is _exactly_ causing the conflict, but I'm guessing it somehow makes the `~/.norminette/norminette.rb` file inaccessible for norminette-vim after it changes the working directory? But how...

**Comment by alexandregv** [comment] 2021-02-15 06:18
Nice catch!

`~/.norminette/norminette.rb` is ok since "Not a valid file" is an error returned by norminette. The problem is with the opened file (`test.c`). My guess is that syntastic/norminette-vim gets a wrong filepath because of vim-rooter, which causes a "Not a valid file" error (norminette returns this error in case of non-existing file).

Probably something like
```
$> pwd
/home/user
$> git init
$> mkdir test && cd test
$> git init
$> vim test.c
# ...
# Current filepath = ./test.c
# vim-rooter changes cwd to /home/user/
# New filepath = ./test/test.c
# norminette-vim tries to load ./test.c instead of ./test/test.c
```

It seems that other people had the same problem with other plugins: https://github.com/airblade/vim-rooter/issues/60#issuecomment-278174164

Maybe try setting `let g:rooter_use_lcd=1` ?
I can't test on my side right now

**Comment by mohamedhaddi** [comment] 2021-02-15 13:17
Apparently the incompatibility issues opened in [airblade/vim-rooter](https://github.com/airblade/vim-rooter) are [related to symbolic links](https://github.com/airblade/vim-rooter/issues/60#issuecomment-297073627) which I believe isn't the case in my issue, I did still try the suggested workarounds (including `let g:rooter_use_lcd=1`) but none have made any change.

>  My guess is that syntastic/norminette-vim gets a wrong filepath because of vim-rooter, which causes a "Not a valid file" error (norminette returns this error in case of non-existing file).

Makes sense! Not sure if it's a bug with vim-rooter, norminette-vim or syntastic, sounds tricky...

**Comment by alexandregv** [comment] 2021-02-18 00:21
Well, I think the real problem is on syntastic or rooter side since I don't manually run the linter or define the filepath in norminette-vim, I just configure the linter

I tried to reproduce the issue with vim-rooter on my arch install but I couldn't, everything is working fine for me (not tested on WSL, no windows near me right now)
Maybe I could fix the issue by getting the working directory with `getcwd()` and setting it to the `cwd` option of syntastic, but it's hard to test if I can't reproduce the issue :/

**Comment by mohamedhaddi** [comment] 2021-02-18 12:05
> I tried to reproduce the issue with vim-rooter on my arch install but I couldn't, everything is working fine for me (not tested on 
WSL, no windows near me right now)

Bummer! Could it be WSL or Debian specific? Did you ensure that you're testing on nested repositories like you did first?

To test again I have removed any other configuration or plugin and this is all what's inside `init.vim` with nothing else added manually in either `nvim/plugin/` or `nvim/ftplugin/`:

```vim
call plug#begin('~/.config/nvim/plugged')

Plug 'airblade/vim-rooter'
Plug 'alexandregv/norminette-vim'
Plug 'vim-syntastic/syntastic'

call plug#end()

" === norminette-vim === "
" Enable norminette-vim (and clang)
let g:syntastic_c_checkers = ['norminette', 'clang']
let g:syntastic_aggregate_errors = 1

" Set the path to norminette (do no set if using norminette of 42 mac)
let g:syntastic_c_norminette_exec = '~/.norminette/norminette.rb'

" Support headers (.h)
let g:c_syntax_for_h = 1
let g:syntastic_c_include_dirs = ['include', '../include', '../../include', 'libft', '../libft/include', '../../libft/include']

" Pass custom arguments to norminette
let g:syntastic_c_norminette_args = '-R CheckForbiddenSourceHeader'

" Check errors when opening a file (disable to speed up startup time)
let g:syntastic_check_on_open = 1

" Enable error list
let g:syntastic_always_populate_loc_list = 1

" Automatically open error list
let g:syntastic_auto_loc_list = 1

" Skip check when closing
let g:syntastic_check_on_wq = 0
```

Result:
![image](https://user-images.githubusercontent.com/6943864/108352215-d67f0f00-71e6-11eb-8594-421d7527620e.png)

After commenting out `Plug 'airblade/vim-rooter'`:
![image](https://user-images.githubusercontent.com/6943864/108352323-f6163780-71e6-11eb-9010-abb668a292fb.png)

> Maybe I could fix the issue by getting the working directory with getcwd() and setting it to the cwd option of syntastic, but it's hard to test if I can't reproduce the issue :/

I can share with you the debug messages if you'd be interested.

**Comment by mohamedhaddi** [comment] 2021-02-18 12:21
These are the debug messages for the following flags: "trace general workflow (1)" and "dump location lists (2)", let me know if you need me to get more details:

(Testing on the same file as above: `$HOME/test/test.c` where `$HOME/` and `test/` are both git repositories)
```
syntastic: 0.443823: g:syntastic_version = '3.10.0-22 (Vim 800, Neovim, Linux)'
syntastic: 0.444494: &shell = '/usr/bin/fish', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
syntastic: 0.445719: UpdateErrors (auto): default checkers
syntastic: 0.446455: CacheErrors: default checkers
syntastic: 0.447341: g:syntastic_aggregate_errors = 1
syntastic: 0.447744: getcwd() = '/home/haddi/test'
syntastic: 0.453520: CacheErrors: Invoking checker: c/norminette
syntastic: 0.454487: SyntasticMake: called with options: {'Preprocess': 'Norminette_vim_preprocess', 'errorformat': '%PNorme: %f,%t%.%# (line %l\, col %c): %m,%t%.%# (line %l): %m,%Q,%P%f: KO!,%.%#(line: %l\, col: %c): %m,%.%#(line: %l):%m,%Q,', 'makeprg': '/home/haddi/.norminette/norminette.rb -R CheckForbiddenSourceHeader test.c', 'env': {'RUBYOPT': '-W0'}}
syntastic: 2.158216: system: command run in 1.702892s
syntastic: 2.158910: checker output: ['Norme: ./test.c', 'Warning: Not a valid file', '']
syntastic: 2.160511: preprocess (external): ['Norme: ./test.c', 'Warning (line 1): Not a valid file', '']
syntastic: 2.162596: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}, {'lnum': 1, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'W', 'pattern': '', 'text': 'Not a valid file'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}]
syntastic: 2.164442: getLocList: checker c/norminette returned 0
syntastic: 2.165323: c/norminette raw: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}, {'lnum': 1, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'W', 'pattern': '', 'text': 'Not a valid file'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}]
syntastic: 2.166724: quiet_messages filter: {}
syntastic: 2.167833: getLocList: checker c/norminette run in 1.714033s
syntastic: 2.169249: aggregated: {'_sorted': 0, '_name': 'norminette (c)', '_owner': 1, '_columns': 1, '_rawLoclist': [{'lnum': 1, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'W', 'pattern': '', 'text': 'Not a valid file [c/norminette]'}]}
syntastic: 2.170406: sorted: {'_sorted': 1, '_name': 'norminette (c)', '_owner': 1, '_columns': 1, '_rawLoclist': [{'lnum': 1, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'scol': 0, 'nr': -1, 'module': '', 'type': 'W', 'pattern': '', 'text': 'Not a valid file [c/norminette]'}]}
```

And these are the messages for the same debugging flags when I disable vim-rooter:

```
syntastic: 0.461038: g:syntastic_version = '3.10.0-22 (Vim 800, Neovim, Linux)'
syntastic: 0.461453: &shell = '/usr/bin/fish', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
syntastic: 0.463701: UpdateErrors (auto): default checkers
syntastic: 0.464544: CacheErrors: default checkers
syntastic: 0.465467: g:syntastic_aggregate_errors = 1
syntastic: 0.465901: getcwd() = '/home/haddi'
syntastic: 0.474548: CacheErrors: Invoking checker: c/norminette
syntastic: 0.476023: SyntasticMake: called with options: {'Preprocess': 'Norminette_vim_preprocess', 'errorformat': '%PNorme: %f,%t%.%# (line %l\, col %c): %m,%t%.%# (line %l): %m,%Q,%P%f: KO!,%.%#(line: %l\, col: %c): %m,%.%#(line: %l):%m,%Q,', 'makeprg': '/home/haddi/.norminette/norminette.rb -R CheckForbiddenSourceHeader test/test.c', 'env': {'RUBYOPT': '-W0'}}
syntastic: 2.231840: system: command run in 1.754899s
syntastic: 2.232534: checker output: ['Norme: ./test/test.c', 'Error (line 13): Space before function name', 'Error (line 13): missing void in function main', 'Error (line 13, col 11): no newline before block', 'Error (line 14, col 8): missing parentheses in return statement', '']
syntastic: 2.233999: preprocess (external): ['Norme: ./test/test.c', 'Error (line 13): Space before function name', 'Error (line 13): missing void in function main', 'Error (line 13, col 11): no newline before block', 'Error (line 14, col 8): missing parentheses in return statement', '']
syntastic: 2.236885: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}, {'lnum': 13, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'E', 'pattern': '', 'text': 'Space before function name'}, {'lnum': 13, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'E', 'pattern': '', 'text': 'missing void in function main'}, {'lnum': 13, 'bufnr': 1, 'col': 11, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'E', 'pattern': '', 'text': 'no newline before block'}, {'lnum': 14, 'bufnr': 1, 'col': 8, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'E', 'pattern': '', 'text': 'missing parentheses in return statement'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}]
syntastic: 2.238301: getLocList: checker c/norminette returned 0
syntastic: 2.239012: c/norminette raw: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}, {'lnum': 13, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'E', 'pattern': '', 'text': 'Space before function name'}, {'lnum': 13, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'E', 'pattern': '', 'text': 'missing void in function main'}, {'lnum': 13, 'bufnr': 1, 'col': 11, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'E', 'pattern': '', 'text': 'no newline before block'}, {'lnum': 14, 'bufnr': 1, 'col': 8, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'E', 'pattern': '', 'text': 'missing parentheses in return statement'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}]
syntastic: 2.240188: quiet_messages filter: {}
syntastic: 2.240725: getLocList: checker c/norminette run in 1.765791s
syntastic: 2.245012: aggregated: {'_sorted': 0, '_name': 'norminette (c)', '_owner': 1, '_columns': 1, '_rawLoclist': [{'lnum': 13, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'E', 'pattern': '', 'text': 'Space before function name [c/norminette]'}, {'lnum': 13, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'E', 'pattern': '', 'text': 'missing void in function main [c/norminette]'}, {'lnum': 13, 'bufnr': 1, 'col': 11, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'E', 'pattern': '', 'text': 'no newline before block [c/norminette]'}, {'lnum': 14, 'bufnr': 1, 'col': 8, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'E', 'pattern': '', 'text': 'missing parentheses in return statement [c/norminette]'}]}
syntastic: 2.247491: sorted: {'_sorted': 1, '_name': 'norminette (c)', '_owner': 1, '_columns': 1, '_rawLoclist': [{'lnum': 13, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'scol': 0, 'nr': -1, 'module': '', 'type': 'E', 'pattern': '', 'text': 'Space before function name [c/norminette]'}, {'lnum': 13, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'scol': 0, 'nr': -1, 'module': '', 'type': 'E', 'pattern': '', 'text': 'missing void in function main [c/norminette]'}, {'lnum': 13, 'bufnr': 1, 'col': 11, 'valid': 1, 'vcol': 0, 'scol': 11, 'nr': -1, 'module': '', 'type': 'E', 'pattern': '', 'text': 'no newline before block [c/norminette]'}, {'lnum': 14, 'bufnr': 1, 'col': 8, 'valid': 1, 'vcol': 0, 'scol': 11, 'nr': -1, 'module': '', 'type': 'E', 'pattern': '', 'text': 'missing parentheses in return statement [c/norminette]'}]}
```

**Comment by mohamedhaddi** [comment] 2021-02-18 13:06
This is getting more confusing! I just made a little discovery now when I tried to instead of opening the file `~/test/test.c` from my home directory I `cd`ed into `test/` and opened `test.c` from there, in this case it gives the same error ***even when I disable vim-rooter!***

Debug messages with vim-rooter enabled:
```
syntastic: 0.488777: g:syntastic_version = '3.10.0-22 (Vim 800, Neovim, Linux)'
syntastic: 0.489308: &shell = '/usr/bin/fish', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
syntastic: 0.491538: UpdateErrors (auto): default checkers
syntastic: 0.492436: CacheErrors: default checkers
syntastic: 0.493329: g:syntastic_aggregate_errors = 1
syntastic: 0.493734: getcwd() = '/home/haddi/test'
syntastic: 0.502196: CacheErrors: Invoking checker: c/norminette
syntastic: 0.503231: SyntasticMake: called with options: {'Preprocess': 'Norminette_vim_preprocess', 'errorformat': '%PNorme: %f,%t%.%# (line %l\, col %c): %m,%t%.%# (line %l): %m,%Q,%P%f: KO!,%.%#(line: %l\, col: %c): %m,%.%#(line: %l):%m,%Q,', 'makeprg': '/home/haddi/.norminette/norminette.rb -R CheckForbiddenSourceHeader test.c', 'env': {'RUBYOPT': '-W0'}}
syntastic: 2.239411: system: command run in 1.735464s
syntastic: 2.239992: checker output: ['Norme: ./test.c', 'Warning: Not a valid file', '']
syntastic: 2.241227: preprocess (external): ['Norme: ./test.c', 'Warning (line 1): Not a valid file', '']
syntastic: 2.243039: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}, {'lnum': 1, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'W', 'pattern': '', 'text': 'Not a valid file'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}]
syntastic: 2.244442: getLocList: checker c/norminette returned 0
syntastic: 2.245138: c/norminette raw: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}, {'lnum': 1, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'W', 'pattern': '', 'text': 'Not a valid file'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}]
syntastic: 2.246401: quiet_messages filter: {}
syntastic: 2.247180: getLocList: checker c/norminette run in 1.744592s
syntastic: 2.249304: aggregated: {'_sorted': 0, '_name': 'norminette (c)', '_owner': 1, '_columns': 1, '_rawLoclist': [{'lnum': 1, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'W', 'pattern': '', 'text': 'Not a valid file [c/norminette]'}]}
syntastic: 2.253214: sorted: {'_sorted': 1, '_name': 'norminette (c)', '_owner': 1, '_columns': 1, '_rawLoclist': [{'lnum': 1, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'scol': 0, 'nr': -1, 'module': '', 'type': 'W', 'pattern': '', 'text': 'Not a valid file [c/norminette]'}]}
```

Debug messages with vim-rooter disabled (when opening the file from its directory instead of opening it from `$HOME`), they are apparently the exact same messages:
```
syntastic: 0.432521: g:syntastic_version = '3.10.0-22 (Vim 800, Neovim, Linux)'
syntastic: 0.433023: &shell = '/usr/bin/fish', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
syntastic: 0.434409: UpdateErrors (auto): default checkers
syntastic: 0.435118: CacheErrors: default checkers
syntastic: 0.436053: g:syntastic_aggregate_errors = 1
syntastic: 0.436512: getcwd() = '/home/haddi/test'
syntastic: 0.441950: CacheErrors: Invoking checker: c/norminette
syntastic: 0.444098: SyntasticMake: called with options: {'Preprocess': 'Norminette_vim_preprocess', 'errorformat': '%PNorme: %f,%t%.%# (line %l\, col %c): %m,%t%.%# (line %l): %m,%Q,%P%f: KO!,%.%#(line: %l\, col: %c): %m,%.%#(line: %l):%m,%Q,', 'makeprg': '/home/haddi/.norminette/norminette.rb -R CheckForbiddenSourceHeader test.c', 'env': {'RUBYOPT': '-W0'}}
syntastic: 2.123242: system: command run in 1.678229s
syntastic: 2.124264: checker output: ['Norme: ./test.c', 'Warning: Not a valid file', '']
syntastic: 2.125489: preprocess (external): ['Norme: ./test.c', 'Warning (line 1): Not a valid file', '']
syntastic: 2.127437: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}, {'lnum': 1, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'W', 'pattern': '', 'text': 'Not a valid file'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}]
syntastic: 2.128764: getLocList: checker c/norminette returned 0
syntastic: 2.129866: c/norminette raw: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}, {'lnum': 1, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'W', 'pattern': '', 'text': 'Not a valid file'}, {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}]
syntastic: 2.131189: quiet_messages filter: {}
syntastic: 2.132024: getLocList: checker c/norminette run in 1.689712s
syntastic: 2.134995: aggregated: {'_sorted': 0, '_name': 'norminette (c)', '_owner': 1, '_columns': 1, '_rawLoclist': [{'lnum': 1, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'nr': -1, 'module': '', 'type': 'W', 'pattern': '', 'text': 'Not a valid file [c/norminette]'}]}
syntastic: 2.136823: sorted: {'_sorted': 1, '_name': 'norminette (c)', '_owner': 1, '_columns': 1, '_rawLoclist': [{'lnum': 1, 'bufnr': 1, 'col': 0, 'valid': 1, 'vcol': 0, 'scol': 0, 'nr': -1, 'module': '', 'type': 'W', 'pattern': '', 'text': 'Not a valid file [c/norminette]'}]}
```

So apparently it has less to do with vim-rooter and more to do with something else related to either how it deals with directories or paths or WSL, but I don't understand what's the issue since `getcwd() = '/home/haddi/test'` seems right and `'makeprg': '/home/haddi/.norminette/norminette.rb -R CheckForbiddenSourceHeader test.c'` seems right as well if it is indeed being run in cwd, running this same command on my command line within `/home/haddi/test` works without issue:

![image](https://user-images.githubusercontent.com/6943864/108361622-06ccaa80-71f3-11eb-84d2-fd42ec22f94f.png)

**Comment by mohamedhaddi** [comment] 2021-02-19 21:44
Following up the last comment, here are two videos both with _vim-rooter_ disabled, and both on the same file `$HOME/test/test.c` where `$HOME` and `test/` are both git repositories, the only difference is that in the first one I open the file from `$HOME`, whereas in the second one I open it from `test/`. 

The videos show that _norminette-vim_ works in both cases, but the issue is with _syntastic_ in the second one, _syntastic_ just doesn't get the correct file path for some reason that doesn't even involve _vim-rooter_.

**1:**

https://user-images.githubusercontent.com/6943864/108564571-9eb9b980-7303-11eb-82e0-f2e2e4c82d08.mp4

**2:**

https://user-images.githubusercontent.com/6943864/108564682-cad53a80-7303-11eb-8df7-bcc339649993.mp4

**Comment by alexandregv** [comment] 2021-02-19 22:49
Well, this is really weird since looking at debug infos, cwd and makeprg seem correct..

If you can reproduce this bug with other syntastic linters, you should probably open an issue on syntastic repo.
Otherwise, I don't really see how I could fix this, and I can't manage to reproduce the bug on my setup, so this is really hard to debug and fix.

Btw thanks for all your efforts, I appreciate this.

**Comment by alexandregv** [comment] 2022-09-24 16:49
Since this problem seems to only affect norminette v2 (ruby) and the official version is now v3 (python) everywhere for more than a year, I will close this issue.

**Closed as completed by alexandregv** 2022-09-24 16:49 UTC
Labels: bug
